mediabrowser/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url('^images/$', views.image_list_view , name='mediabrowser-image-list'),
    url('^images/add/$', views.image_add_view, name='mediabrowser-add-image'),
    
    url('^documents/$', views.document_list_view, name='mediabrowser-document-list'),
    url('^documents/images/$', views.image_as_document_list_view, name='mediabrowser-image-document-list'),
    url('^documents/add/$', views.document_add_view, name='mediabrowser-add-document'),
    
    url('^delete/$', views.asset_delete_view, name='mediabrowser-delete'),
]

mediabrowser/models.py
from PIL import Image
from django.db import models
from django.conf import settings
import os.path
from .constants import MEDIABROWSER_UPLOAD_TO, ASSET_TYPE_CHOICES

import re

_ = lambda x:x

class Asset(models.Model):
    name = models.TextField(_("name"), max_length=120)
    file = models.FileField(_("file"), upload_to=MEDIABROWSER_UPLOAD_TO)
    type = models.CharField(_("type"), max_length=16, choices=ASSET_TYPE_CHOICES)
    ext = models.CharField(_("type"), max_length=40)
    uploaded_on = models.DateTimeField(_("uploaded on"), auto_now_add=True)
    uploaded_by = models.CharField(_("uploaded by"), max_length=80, blank=True)
    width = models.PositiveIntegerField(_("width"), blank=True, null=True)
    height = models.PositiveIntegerField(_("height"), blank=True, null=True)

    
    def save(self, *args, **kwargs):
        request = kwargs.pop("request", None)
        if request and not self.uploaded_by:
            self.uploaded_by = unicode(request.user)
            
        if not self.name:
            m = re.search(r'([^/]+)$', self.file.url)
            self.name = m.group(1)
            self.name = re.sub(r'(_|-|%20)+', ' ', self.name)
            
        if not self.ext:
            m = re.search(r'(\w+)$', self.name)
            if m:
                self.ext = m.group(1).lower()
            
        if self.ext in ('png','jpg','jpeg','gif'):
            # we treat tiff, bmp and other image types as documents
            self.type = "img"
        else:
            self.type = "doc"
        
        resize_to = None
        img = None
        
        if self.type == "img" and not self.id:
            self.file.open('rb')
            img = Image.open(self.file)
            (imgW, imgH) = img.size
            max_size = getattr(settings, "MEDIABROWSER_MAX_IMAGE_SIZE", None)
            if max_size:
                if imgW > max_size[0] or imgH > max_size[1]:    
                    ratio = max(float(imgW)/max_size[0], float(imgH)/max_size[1])
                    resize_to = (int(imgW/ratio), int(imgH/ratio))
            
            if resize_to:
                self.width, self.height = resize_to
            else:
                self.width, self.height = img.size
        
        super(Asset, self).save(*args, **kwargs)
        
        if resize_to and img:
            img.resize(resize_to, Image.ANTIALIAS).save(self.file.path, img.format)
    
    def __unicode__(self):
        if self.type == "img":
            return '%s, %d x %d' % (self.name, self.width, self.height)
        return self.name

mediabrowser/templates/mediabrowser/add.html
{% extends "mediabrowser/base.html" %}
{% load i18n %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="file" id="id_file">
    <input id="UploadFile" type="submit" value="{% trans "Choose a file on your computer" %}">
</form>

{% endblock %}

mediabrowser/templates/mediabrowser/add_success.html
{% extends "mediabrowser/base.html" %}
{% load i18n %}

{% block content %}

<script>
    $(function(){
        MEDIABROWSER.insertFile('{{ asset.file.url }}');
        window.close();
    });
</script>

{% endblock %}

mediabrowser/templates/mediabrowser/base.html
<!DOCTYPE html>
{% load i18n %}
{% load static from staticfiles %}
{% get_current_language as LANG_CODE %}
<html lang="{{ LANG_CODE }}">
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <title>{% trans "Media browser" %}</title>    
    <script src="{% static 'mediabrowser/js/jquery-1.9.1.js' %}"></script>
    <script src="{% static 'mediabrowser/js/jquery-ui-1.10.3.custom.min.js' %}"></script>
    <script src="{% static 'mediabrowser/js/mediabrowser.js' %}"></script>
    {% block head %}{% endblock %}
    {% include "mediabrowser/includes/css.html" %}
    {% include "mediabrowser/includes/head.html" %}
</head>
<body>
    <div id="MediaBrowserNavigation">
        {% if asset_type == "img" %}
            {% if can_upload %}<a href="{% url 'mediabrowser-add-image' %}?{{ QUERY_STRING }}">{% trans "Upload" %}</a>{% endif %}
            <a href="{% url 'mediabrowser-image-list' %}?{{ QUERY_STRING }}">{% trans "Browse images" %}</a>
        {% elif asset_type == "doc" %}
            {% if can_upload %}<a href="{% url 'mediabrowser-add-document' %}?{{ QUERY_STRING }}">{% trans "Upload" %}</a>{% endif %}
            <a href="{% url 'mediabrowser-document-list' %}?{{ QUERY_STRING }}">{% trans "Browse documents" %}</a>
            <a href="{% url 'mediabrowser-image-document-list' %}?{{ QUERY_STRING }}">{% trans "Browse images" %}</a>
            {% if page_selector_url %}
            <a href="{% url page_selector_url %}?{{ QUERY_STRING }}">{% trans "Browse content" %}</a>
            {% endif %}
        {% endif %}
    </div>
    <div id="MediaBrowserContent">
        {% block content %}{% endblock %}
    </div>
    {% block footer %}{% endblock %}
</body>
</html>

mediabrowser/templates/mediabrowser/list.html
{% extends 'mediabrowser/base.html' %}
{% load i18n %}

{% block content %}
    {% include "mediabrowser/includes/asset-listing.html" %}
{% endblock %}


{% block footer %}
    <div id="ButtonBar">
        <a id="InsertFile" class="inactive button" href="#">{% trans "Insert" %}</a>
        {% if can_delete %}<a id="DeleteFile" class="inactive button" href="#">{% trans "Delete" %}</a>{% endif %}
    </div>    

    {% if can_delete %}
    <div id="ConfirmDeleteDialog" title="{% trans 'Delete this file?' %}">
        <p>{% trans "Are you sure you would like to delete this file:" %}</p>
        <p id="FileToBeDeletedContent"></p>
        <form action="{% url 'mediabrowser-delete' %}" method="post" id="AssetDeletionForm">
            {% csrf_token %}
            <input type="hidden" name="asset_id" id="FileIdToBeDeleted">
            <input type="submit" value="{% trans 'Delete' %}">
            <a href="#" class="ui-dialog-cancel">{% trans "Cancel" %}</a>
        </form>
    </div>
    {% endif %}
{% endblock %}